### ISSUE TITLE
ESP32 bootloader.bin not found when flashing

### ISSUE THREAD

**Issue by vtothsvk** [mahavirj/zephyr#1]
**Describe the bug**
Hi!
I was trying out the [WiFi support for ESP32](https://github.com/zephyrproject-rtos/zephyr/issues/3723) and encountered the following issue: each time I build an app and try to flash it I get an error pointing that no bootloader.bin is present in the build (no partitions file is generated as well). Tried the CONFIG_BOOTLOADER_ESP_IDF=y option as well, still no bootloader is being built.

**To Reproduce**
1. west build -b esp32 -s samples/net/dhcpv4_client/
2. west flash --esp-device [device COM port]

**Expected behavior**
Build and flash the dhcpv4_client app

**Impact**
Been tackling this one for some time of this week so any help would be much appreciated :) .

**Logs and console output**
```
C:\Users\epic_\zephyrproject>west flash --esp-device COM11
-- west flash: rebuilding
[0/1] cmd.exe /C "cd /D C:\Users\epic_\zephyrproject\build\zephyr\cmake\flash && "C:\Program Files\CMake\bin\cmake.exe" -E echo "

-- west flash: using runner esp32
-- runners.esp32: Converting ELF to BIN
esptool.py v3.0-dev
-- runners.esp32: Flashing ESP32 on COM11 (921600bps)
usage: esptool write_flash [-h] [--erase-all] [--flash_freq {keep,40m,26m,20m,80m}] [--flash_mode {keep,qio,qout,dio,dout}] [--flash_size FLASH_SIZE] [--spi-connection SPI_CONNECTION] [--no-progress]
                           [--verify] [--encrypt] [--ignore-flash-encryption-efuse-setting] [--compress | --no-compress]
                           <address> <filename> [<address> <filename> ...]
esptool write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: 'C:/Users/epic_/zephyrproject/build/esp-idf/build/bootloader/bootloader.bin'
FATAL ERROR: command exited with status 2: 'c:\python38\python.exe' 'C:\Users\epic_\zephyrproject\modules\hal\espressif\components\esptool_py\esptool\esptool.py' --chip esp32 --port COM11 --baud 921600 --before default_reset --after hard_reset write_flash -u --flash_mode dio --flash_freq 40m --flash_size detect 0x1000 C:/Users/epic_/zephyrproject/build/esp-idf/build/bootloader/bootloader.bin 0x8000 C:/Users/epic_/zephyrproject/build/esp-idf/build/partitions_singleapp.bin 0x10000 'C:\Users\epic_\zephyrproject\build\zephyr\zephyr.bin'
```

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - Toolchain xtensa-esp32-elf-gcc 8.4.0 (tried 8.2.0 as well)
 - Commit SHA [a96a1e2](https://github.com/mahavirj/zephyr/commit/a96a1e2f4cac18cf9bf256af4324620b1cec13c7)

**Comment by mahavirj** [comment]
@vtothsvk Can you please check if `bootloader.bin` exists at `C:/Users/epic_/zephyrproject/build/esp-idf/build/bootloader/bootloader.bin` in your case? You can maybe quickly iterate through `build` directory to list down all generated artifacts. I am asking just to ensure that this is related to flashing and not actual build itself.

**Comment by vtothsvk** [comment]
No, the bootloader and the partition bins are absent, so it seems they are not built at all

**Comment by mahavirj** [comment]
Thanks for update. Can you please attach entire build log here?

**Comment by vtothsvk** [comment]
Sure
[building-log.txt](https://github.com/mahavirj/zephyr/files/5555659/building-log.txt)
also here is the whole generated build directory
[build.zip](https://github.com/mahavirj/zephyr/files/5555911/build.zip)

**Comment by shubhamkulkarni97** [comment]
Hi @vtothsvk, I could reproduce this issue on Windows machine.

We are looking into the issue and will get back to you.

**Comment by shubhamkulkarni97** [comment]
@vtothsvk, make support is removed from ESP-IDF v4.x version when building on Windows. As the bootloader is build using make command, it causes issue on Windows machines. Hence, we must use CMake to build ESP-IDF bootloader.

Please try applying attached patch and check if you can build and flash the application.

Please make sure that `ESP_IDF_PATH` environment variable point to `hal_espressif` directory.

Additional step required in [environment setup](https://github.com/mahavirj/zephyr/wiki/ESP32-Getting-Started-Guide) is to make sure `IDF_PATH` environment variable is not set.

[0001-Use-cmake-to-build-ESP-IDF-bootloader-make-builds-ar.patch.zip](https://github.com/mahavirj/zephyr/files/5571501/0001-Use-cmake-to-build-ESP-IDF-bootloader-make-builds-ar.patch.zip)

Thanks,
Shubham

**Comment by vtothsvk** [comment]
@shubhamkulkarni97 Thanks to your patch, the bootloader is now built as intended and I got the dhcpv4_client example running.

Thank you
Viktor
